name: Deploy Docs

on:
  push:
    branches:
      # 当 main 分支发生提交时触发 actions
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      # 安装依赖
      - name: Install Deps
        run: npm install

      # 构建
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run docs:build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # gh-pages 分支下的构建目录
          branch: gh-pages
          folder: docs/.vuepress/dist

  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Configuration environment
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keyscan -H monkee.online >> ~/.ssh/known_hosts
          git config --global user.name 'Nevermore'
          git config --global user.email 'Nevermorey98@gmail.com'

      - name: Deploy
        run: |
          git push -f git@mrhope.site:/home/www/website/blog.git gh-pages
          ssh git@monkee.online "cd /home/www/website/blog && git reset --hard HEAD"
